<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio__15._1
{


    public partial class _Default
    {
    }
}
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio__15._1
{


    public partial class _Default
    {
    }
}
>>>>>>> 3508c144e3f7c6cb28bcb432fc83f806220353a7
